# Generated by Django 5.2.3 on 2025-07-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_remove_restaurant_paylink_account_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='robokassa_shop_code',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='robokassa_login',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Логин ресторана в Robokassa'),
        ),
    ]
