# Generated by Django 5.2.3 on 2025-07-01 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_restaurant_latitude_restaurant_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Название тарифа (например, 'Дневной')")),
                ('start_time', models.TimeField(verbose_name='Время начала действия')),
                ('end_time', models.TimeField(verbose_name='Время окончания действия')),
                ('base_fee', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Базовая стоимость (тг)')),
                ('fee_per_km', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Стоимость за км (тг)')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariffs', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Тариф на доставку',
                'verbose_name_plural': 'Тарифы на доставку',
                'ordering': ['start_time'],
            },
        ),
    ]
