# Generated by Django 5.2.3 on 2025-07-09 19:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenizationAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('successful', 'Успешно'), ('failed', 'Неудачно')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paylink_checkout_token', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Моя карта', max_length=50, verbose_name='Название карты')),
                ('card_type', models.CharField(default='Visa', max_length=50)),
                ('last_four', models.CharField(max_length=4, verbose_name='Последние 4 цифры')),
                ('expiry_month', models.CharField(max_length=2, verbose_name='Месяц окончания')),
                ('expiry_year', models.CharField(max_length=4, verbose_name='Год окончания')),
                ('card_token', models.CharField(max_length=255, unique=True, verbose_name='Токен карты')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Основная карта')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Платежная карта',
                'verbose_name_plural': 'Платежные карты',
                'ordering': ['-is_primary', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('user',), name='unique_primary_card_for_user')],
            },
        ),
    ]
