# Generated by Django 5.2.3 on 2025-07-12 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tokenizationattempt',
            name='user',
        ),
        migrations.DeleteModel(
            name='PaymentCard',
        ),
        migrations.DeleteModel(
            name='TokenizationAttempt',
        ),
    ]
