# Generated by Django 5.2.3 on 2025-07-14 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0002_remove_tokenizationattempt_user_delete_paymentcard_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedUserCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_token', models.CharField(max_length=255, unique=True, verbose_name='Токен карты PayLink')),
                ('card_mask', models.CharField(max_length=20, verbose_name='Маска карты (e.g., 5100...1234)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сохраненная карта',
                'verbose_name_plural': 'Сохраненные карты',
            },
        ),
    ]
