# Generated by Django 5.2.3 on 2025-06-28 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notifications_enabled',
            field=models.BooleanField(default=True, verbose_name='Основные уведомления'),
        ),
        migrations.AddField(
            model_name='user',
            name='promotions_enabled',
            field=models.BooleanField(default=True, verbose_name='Рекламные уведомления'),
        ),
    ]
