# Generated by Django 5.2.3 on 2025-07-13 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Номер телефона')),
                ('otp', models.CharField(max_length=4, verbose_name='OTP код')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
            ],
            options={
                'verbose_name': 'OTP код',
                'verbose_name_plural': 'OTP коды',
            },
        ),
    ]
