# Generated by Django 5.2.3 on 2025-07-15 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_phoneotp'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='address',
            name='unique_primary_address_for_user',
        ),
        migrations.RemoveField(
            model_name='address',
            name='full_address',
        ),
        migrations.RemoveField(
            model_name='address',
            name='title',
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(default='Unknown', max_length=100, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='address',
            name='house_number',
            field=models.CharField(default='Unknown', max_length=20, verbose_name='Номер дома'),
        ),
        migrations.AddField(
            model_name='address',
            name='street',
            field=models.CharField(default='Unknown', max_length=255, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='address',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL),
        ),
    ]
