# Generated by Django 5.2.3 on 2025-07-02 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_address_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта курьера'),
        ),
        migrations.AddField(
            model_name='user',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота курьера'),
        ),
    ]
