# Generated by Django 5.2.3 on 2025-07-11 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courierprofile',
            name='paylink_account_id',
        ),
        migrations.AddField(
            model_name='courierprofile',
            name='robokassa_shop_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Robokassa Shop Code'),
        ),
    ]
