# Generated by Django 5.2.3 on 2025-07-09 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0002_initial'),
        ('promos', '0001_initial'),
        ('restaurants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, unique=True)),
                ('address', models.TextField()),
                ('delivery_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('delivery_lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('comment', models.TextField(blank=True, default='')),
                ('items_total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма по товарам')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость доставки')),
                ('service_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сервисный сбор')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Итоговая сумма к оплате')),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Прибыль платформы')),
                ('restaurant_payout', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Выплата ресторану')),
                ('courier_payout', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Выплата курьеру')),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('accepted', 'Принят'), ('preparing', 'Готовится'), ('ready_for_pickup', 'Готов к выдаче'), ('on_the_way', 'В пути'), ('delivered', 'Доставлен'), ('cancelled', 'Отменен')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(choices=[('card_online', 'Картой онлайн'), ('cash', 'Наличными')], default='card_online', max_length=20)),
                ('is_paid', models.BooleanField(default=False)),
                ('payment_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='UID платежа в PayLink')),
                ('authorization_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID авторизации в PayLink')),
                ('preparation_time', models.PositiveIntegerField(blank=True, help_text='Время готовки в минутах', null=True)),
                ('estimated_delivery_time', models.DateTimeField(blank=True, null=True)),
                ('courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to=settings.AUTH_USER_MODEL)),
                ('promo_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='promos.promocode')),
                ('restaurant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='restaurants.restaurant')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price_at_time_of_order', models.DecimalField(decimal_places=2, max_digits=10)),
                ('menu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.dish')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
        ),
    ]
