# Generated by Django 5.2.3 on 2025-07-11 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='estimated_delivery_time',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='preparation_time',
        ),
        migrations.RemoveField(
            model_name='order',
            name='promo_code',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_invoice_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID счета в Robokassa'),
        ),
        migrations.AlterField(
            model_name='order',
            name='authorization_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID авторизации (холдирования)'),
        ),
    ]
