# Generated by Django 5.2.3 on 2025-06-26 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_code'),
        ('restaurants', '0002_restaurant_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='restaurants.restaurant'),
        ),
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
