# Generated by Django 5.2.3 on 2025-07-01 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_delivery_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price_at_time_of_order',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена на момент заказа'),
        ),
    ]
