# Generated by Django 5.2.3 on 2025-07-02 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderitem_price_at_time_of_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='estimated_delivery_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Примерное время доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='preparation_time',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Время готовки (мин)'),
        ),
    ]
