# Generated by Django 5.2.3 on 2025-07-02 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_estimated_delivery_time_order_preparation_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_lon',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота доставки'),
        ),
    ]
